version: "3.9"

services:
  db:
    image: mysql:9.0-oracle
    container_name: pl_db
    environment:
      MYSQL_DATABASE: "ProjektLabor"
      MYSQL_USER: "pl_user"
      MYSQL_PASSWORD: "NehezJelszo123!!"
      MYSQL_ROOT_PASSWORD: "RootNehezJelszo123!!"
    ports:
      - "3306:3306"
    volumes:
      - pl_mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build:
      context: ./ProjektLabor
      dockerfile: ProjektLabor/Dockerfile
    container_name: pl_backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=ProjektLabor;User=pl_user;Password=NehezJelszo123!!;"
      Jwt__Key: "uvdnAMv65gxJAb48iwpdBmZ28izwBeGS"
      Jwt__Issuer: "ProjektLabor"
      Jwt__Audience: "ProjektLaborClient"
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./ProjektLabor
      dockerfile: Frontend/Dockerfile
    container_name: pl_frontend
    depends_on:
      - backend
    environment:
      # Vite API base should point to nginx â†’ backend
      VITE_API_BASE_URL: "/api/v1"
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  pl_mysql_data:
